---
title: "Attention, etc"
toc: true
toc-depth: 6
number-sections: true
number-depth: 6
format: html
bibliography: references.bib
engine: jupyter
execute:
   enabled: true
---

## Overview

There are a huge number of other facets of deep learning that we have not covered. These include things such as attention mechanisms, recurrent neural networks, generative adversarial networks, and transformer models. Some of our assigned readings will provde an overview of these, and we will covers a few of these in the final practical and assignment, but most of our hands-on work from here on out will focus on the continued building of our semantic segmentation pipeline.

## Attention

Attention mechanisms are a particular structure in neural networks that are designed to highlight the most essential features to *focus* on in the inputs, and to de-emphasize the least important information. These structures have become increasingly important as they are the building blocks of transformers [@vaswaniAttentionAllYou], which underpin many of the most recent breakthroughs in AI capabilities associated with large language models (LLMs), and more recently for vision-based tasks [@dosovitskiyImageWorth16x162021a]. They are also used to enhance the capabilities of other neural network architectures, including CNNs. Attention mechanisms are covered in section 6 of part 2 of @khallaghi2025 , as well as a [dedicated chapter](https://d2l.ai/chapter_attention-mechanisms-and-transformers/index.html) in Dive Into Deep Learning, and there are a number of good blog posts that cover these. Please read these to learn more about the mechanisms and how they are used. Here we will give a brief summary of attention mechanisms, with a focus on how these connect to CNNs designed for semantic segmentation.

### Attention mechanisms

Attention comes in two forms–hard and soft–with the former being deterministic, and the latter probabilistic and able to be differentiated, which means it can be readily incorporated into models that use backpropagation. An attention mechanism typically has a triplet structure of query (Q), key (K), and value (V), which can be best understood thinking in terms of a relational database (as explained in DiDL). In this analogy, a database consists of a set of keys (K), with each having a corresponding value (V). The database can then be searched with a query (Q) that matches a particular set of keys, so that the associated values can be received. The most important concept to understand is that the matching is done using some function that calculates a set of weights that applies across all keys that indicates the strength of the match between Q and each key. In a database, the weight corresponding to an exact match will equal 1.

This is the general concept for attention in neural networks, but it's a little different. the query is a transformation of the input that represents the current piece to focus on, the key is the other elements on the input to compare the query against in order to find the greatest similarities with the key, which provides attention weights, which are then used to transform the values of the original input.

\[Attention figure\]

normally we use them to approximate the function of responses given
features, now we create a network to approximate attention given
contexts.

Self-attention

Co-attention

Attention example

Attention in encoder-decoder models
