---
title: "Foreword"
---

This course covers the intersection of two large and rapidly expanding fields, Earth Observation (EO, or remote sensing) and deep learning (DL), which is key to the rapidly burgeoning field of artificial intelligence (AI). You will also see that the term GeoAI, or geospatial artificial intelligence, is increasingly used, and encompasses this convergence.  Given the size of these fields (DL/AI and EO), we will only manage to dip the very tips of our toes into these waters. Our goal is to provide you with an intial understanding of some key concepts, including the major classes of deep learning models, the key components of models and how they work, how to apply those models to EO data, and how to interpret the results. A key focus will be on learning the practical skills needed to undertake a deep learning analysis from image pre-processing to model prediction and assessment.

This course is designed with the assumption that you have some familiarity with the concepts and tools used in each field. If you are coming to this class from a data/computer science background, we'll assume that you have already taken some courses in calculus and machine learning, but are less familiar with the ins and outs of satellite image analysis and geospatial concepts. If you are from Geography or an allied discipline, we expect that you will be more familiar with the latter, and less with the former.

Regardless of what academic background you come from, you should have a working knowledge of `python` and programming experience. We will be working extensively in that language, and unfortunately won't have the time to provide instruction in basic programming techniques. Although we will provide some background on several important coding concepts that are not necessarily covered in standard programming classes, and AI-assisted coding is permitted and even encouraged, programming skills are important for developing and running modeling pipelines. Vibe-coding will not get you to your destination--it will take you somewhere, but you won't be sure where you ended up, and it might be hard to backtrack. As an indicator of the baseline programming experience we expect, if we ask you to:

1.  Read the contents of a directory, selecting only files ending in ".csv"
2.  Read the selected files into a list
3.  Then combine those into a DataFrame

You should be able to write something like this fairly quickly (assuming all files have the same columns) without having to ask an LLM:

```python
import os
from pathlib import Path
import pandas as pd

some_dir = "/home/me/some/directory"

csv_files = [Path(some_dir) / file for file in os.listdir(some_dir) 
             if file.endswith(".csv")]
data_list = [pd.read_csv(csv) for csv in csv_files]
data = pd.concat(data_list) 
```
