---
title: "Course Policies"
---

The policies for the class regarding grading, attendance, communications, academic integrity, AI, and University policies related to accessibility, FERPA, and Title IX are provided below. 


## Assessment

Grades in this course will assessed according to four components:

- **Participation**: Determined based on attendance (see next section), contributions to discussion, in-class problem-solving, quizzes, and question sets related to the reading; 
- **Assignments**: There will be three practical coding-based assignments during the semester;
- **Quizzes and exams**: We will give in-class, closed-notes, pen/pencil and paper 1) coding quizzes (at least one) and 2) a pre-project conceptual exam; 
- **Project plan**: A plan describing how your final project team will undertake the
  final project;
- **Final project report**: The final code, analyses, and report for your team
  project.

Each component will be weighted as follows in determining the final grade:

| Component              | DSCI215 | GEOG315 |
|------------------------|---------|---------|
| Participation          | 10%     | 10%     |
| Assignments (3)        | 30%     | 25%     |
| Quizzes and exam       | 25%     | 20%     |
| Final project overview | 5%      | 5%      |
| Final group project    | 30%     | 40%     |

## Attendance

Attendance is mandatory. If you need to miss a class, please arrange with one of the instructors in advance. There will be [**frequent quizzes related to concepts in the assigned reading**]{.underline}**.** These will count towards participation grades.

Another part of attendance is being *present* when in class. Present means you are paying attention to instructors and not looking at your phone or laptop. There is a difference between looking at your laptop for taking notes, and browsing on your laptop. It is very easy to tell the difference from the front of the class room. If you spend most of your time in class just looking at your screen, that will count as an absence.  

## Communications & Organization

-   Class communication will be handled via a dedicated Slack channel. [**The instructors will not use or reply to email**]{.underline}**.**
-   Class material will be handled through a combination of GitHub, Slack, and Google Drive.

## Academic Integrity

The University’s policies on academic integrity will be strictly enforced.
Plagiarism, cheating, lying, stealing, or falsification will not be
tolerated and will be referred to the University Administration. Please
go [here](https://catalog.clarku.edu/content.php?catoid=32&navoid=2735#academic-integrity)
to learn more about this policy and what it entails.

## Technology
### In class
The in-person parts of the course are divided into lecture and lab.  Lectures will be tech free, pen/pencil and paper note-taking, no phone or laptops (exceptions are of course allowed for accommodations), except for the 2-3 (maybe 4) weeks, when we start doing final projects. 

We know this policy might seem odd given that this is a class organized around computation, but there is a fair bit of conceptual material to learn, which in many ways is the most important content, particularly as coding is increasingly handled by agents (see next section).  My experience teaching this course to date is that laptops and phones prove to be too much of a distraction (for some, not all), and the conceptual parts are not well absorbed. The conceptual parts are what help you know whether the model or approach you are choosing is appropriate for the task to which you want to apply it.   

There are other reasons to adopt a tech-free lecture policy, which are summarized in [this New York Times opinion piece](https://www.nytimes.com/2025/11/16/opinion/laptop-classroom-test-scores.html) from last November. Here are some key passages: 

> It seems ridiculous to have to say this, but digital distraction is terrible for academic performance. The more time college students spent doing something else on their laptops during class, [the lower their exam scores](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0251792), even after accounting for academic ability.

And regarding notes:

> Across 24 studies, [college students who took handwritten notes](https://link.springer.com/article/10.1007/s10648-024-09914-w) were 58 percent more likely to get A’s in their courses than those who typed notes on laptops. In contrast, students who typed notes were 75 percent more likely to fail the course than those who wrote them by hand.

Lab will be hands-on coding, and will require your laptops. 

### Use of Artificial Intelligence (AI)
This is a class devoted to learning about the models that underpin AI, and AI-assisted coding is increasingly used by model developers and practitioners as an integral part of their workflow. We will allow and even encourage the use of AI assistants in developing assignments and even your final project. However, we expect the following from you: 1) you show how you used AI as your, which includes documentation of all prompts and responses; 2) that you understand the code you are writing, and do not completely outsource the code yourself. You can code up a complete machine learning pipeline, including a working neural network, quite quickly and run it, but you should understand the model and why it behaves the way it does, which means you have to understand your code. Coding knowledge will be demonstrated by your ability to arrive at correct solutions in your assignments (code completely outsourced to AI will often, if not usually, fail, depending on complexity), and through your grades on a pen and paper coding quiz that we will give. We also reserve the right to give impromptu coding quizzes. 

For any writing that you do, e.g. answering quiz and exam questions, writing introductions, methods sections, results, discussions, or other parts of final projects or assignments, AI use is not permitted. Please note that it is very easy for us to tell when it is and isn't used for writing. 

## Additional Information

### Student Accessibility Services

Clark University is committed to providing students with documented
disabilities equal access to all university programs and facilities.
Students are encouraged to register with Student Accessibility Services
(SAS) to explore and access accommodations that may support their
success in their coursework. SAS is located on the second floor of the
Shaich Family Alumni and Student Engagement Center (ASEC). Please
contact SAS at <accessibilityservices@clarku.edu> with questions or to
initiate the registration process. For additional information, please
visit the [SAS
website](https://www.clarku.edu/offices/student-accessibility-services/).

### FERPA Policy

The link to Clark’s policy regarding student privacy under the Family
Education Rights and Privacy Act is available
[here](https://www.clarku.edu/offices/registrar/ferpa/)

### Title IX

Please be aware that all Clark University faculty and teaching
assistants are considered responsible employees, which means that if you
tell us about a situation involving the aforementioned offenses, we must
share that information with the Title IX Coordinator, Brittany Brickman
(<titleix@clarku.edu>). Although we must make that notification, you
will, for the most part, control how your case will be handled,
including whether or not you wish to pursue a formal complaint. Our goal
is to make sure you are aware of the range of options available to you
and have access to the resources you need. 

If you wish to speak to a confidential resource who does not have this
reporting responsibility, you can contact Clark’s Center for Counseling
and Professional Growth (508-793-7678), Clark’s Health Center
(508-793-7467), or confidential resource providers on campus (see
[here](https://www.clarku.edu/offices/title-ix/resources/) for a list,
and for other resources).