---
title: "Final Projects"
---

The following is an overview of expectations for delivering the final project.  

## Set-up

Work with your team to set up a single private repo on the agroimpacts GitHub organization or one of your personal profiles. One of you can set it up, and then add the rest of you as contributors. Name the repo so that it describes the project, and is all in lowercase with no underscores. Short is better. 

## Key components

### Project description

Make a folder in your repo called "notebooks", and within save a single colab notebook named `description.ipynb`. The notebook should contain the following sections. 

1.  Summary: A brief (up to 250 words) description of the project and its objectives (10 points).
2.  Division of labor: A description of who did what on the project (5 points).
4.  Key findings: A very short summary of key findings (5 points).

Commit the notebook in the repo when you are done with it in colab. You may also wish to do this locally in jupyter notebook/jupyter lab. This notebook is basically an abstract. 

### Primary analyses

Your final project is built in the same repository, following the steps outlined in `description.iypnb`.

Each sub-team in the final project group should have a notebook that lays out the analysis undertaken by the sub-team. For example, in the drone image labeling project, the team developing the cranberry models could have a notebook called `prithvi-finetuning-smallsample.ipynb`, and the group working on cropland mapping with the Lacuna Fund labels could have a notebook called `resunet-train-mostaccurate.ipynb`.

Final notebooks should have the following structure:

1.  Introduction: A brief summary of your sub-team's project objectives (<250 words).
2.  Methods: A summary of the approach used to attain the objectives. E.g. what data you use, how did you process it, what model did you use, and how did you adapt it. This section should be brief but informative. Provide references to code used, etc.
3.  Results/analysis: A brief description of the results, interleaved with any analytical steps. For instance, show:
    -   Your model training/fine-tuning loop.
    -   You evaluation metrics
    -   Prediction code and predictions results (tiles/chips resulting from the prediction step)
4.  Discussion: A brief summary of main findings, any difficulties or surprises encountered, and what improvements could be made.

Each sub-team/contributor should have a notebook that aligns with this structure. If there is a compelling reason to have a different structure, please let us know and we can come to an arrangement.

Note, mark clearly who authored the notebook. If two people are working on the same notebook, please place initials for who did what on that notebook. 

### Repo and code organization

It is acceptable to have all code needed to undertake the sub-team/team project in the relevant notebook, including model code, etc. In this case, we would expect to see the repo organized as `reponame` with one sub-folder named `notebooks`, with the required notebooks (including the original `.ipynb`) in the folder. The structure will look something like this:

    .
    └── reponame/
        ├── README.md
        └── notebooks/
            ├── description.ipynb
            ├── subteam-1.ipynb (named descriptively)
            └── subteam-2.ipynb (named descriptively)

The README should have the project name/brief description of the project, the names of the contributors, and a link to `description.ipynb`.

It may also be preferable for large blocks of reusable code to go into .py files that are loaded as modules from your repo. In this case, the structure would like more like this:

    .
    └── reponame/
        ├── README.md
        ├── notebooks/
        │   ├── plan.ipynb
        │   ├── subteam-1.ipynb (named descriptively)
        │   └── subteam-2.ipynb (named descriptively)
        └── reponame/
            ├── __init__.py
            ├── code1.py (e.g. unet.py)
            └── code2.py (e.g. dataloader.py)

For example, the model architecture, data loader, etc, can all go into a sub-folder in your repo named the same as the repo main folder (**note: see the naming convention for the repo above**). If you have an `__init__.py` file in the folder, then the modules can be imported into your notebooks and used there. In colab, you can clone and read in your repository by placing code such as the following in our notebooks (this example is for cloning \`fieldmapper`` , or for pulling the latest commits into an already existing clone of ` ``deeplearner\`):

```{python}
#| eval: false
# Clone github repository setup
# import join used to join ROOT path and mydrive_path
import os
from os.path import join  

# variables
git_username = "agroimpacts"  # GitHub user/organization name
repo = "fieldmapper"
root = "/content/gdrive/MyDrive/" # set root directory

# save your GitHub access token into a file called "gh.txt", place it in a 
# folder of your choosing. Here we use data/tokens, but change as needed
token_path = f"{root}data/tokens/gh.txt" 
git_token = open(token_path, "r+").read().splitlines()[0]
branch_name = "dev/mc_dropout"

# main path to clone the repo into 
clone_path = f"{root}myprojects"
git_path = f'https://{git_token}@github.com/{git_username}/{repo}.git'
repo_clone_path = f"{clone_path}/{repo}"

# make directory
if not os.path.isdir(clone_path):
    os.makedirs(clone_path)

os.chdir(clone_path)
if not os.path.isdir(repo_clone_path):
    !git clone -b "{branch_name}" "{git_path}"
else:
    if os.listdir(repo_clone_path):
        os.chdir(repo_clone_path)
        !git branch
        !git config core.fileMode false  # needed to ignore permissions changes
        !git pull

os.chdir("..")

```

That will give you access to `fieldmapper`, and then you can import it as follows:

```{python}
#| eval: false

import sys, importlib
sys.path.insert(0, os.path.join(repo_clone_path, 'fieldmapper/'))
sys.path.insert(0, repo_clone_path)
import fieldmapper

# uncomment the line below if you make changes to a module during a 
# a session and want to import those changes
# importlib.reload(fieldmapper) 
from fieldmapper.models import *
from fieldmapper.losses import *
from fieldmapper.datatorch import *
from fieldmapper.utils import *
from fieldmapper.compiler import *
```

The above imports various modules from `fieldmapper`. You can adapt this approach for your own repo.

The first part of the contents of `__init__.py` in `fieldmapper` look like this:

    from .datatorch import *
    from .utils import *
    from .utils_aws import *
    from .compiler import *
    from .models import *
    from .tools import *
    from .losses import *
    from .metrics import BinaryMetrics

A simpler version of that [file](https://github.com/agroimpacts/maputil/blob/main/maputil/__init__.py) is in the [maputil folder](https://github.com/agroimpacts/maputil/tree/main/maputil) of the `maputil` repo:

    from .planet_downloader import *
    from .rasterize_labels import *

You can follow versions of the above to load modules from your own repo. We will award extra points for taking this more structured approach to developing your project repo.

### Exceptions

-  We realize that time is short and some projects are more experimental than others. For example, we know that difficulties might prevent some projects from getting prediction outputs, or even a fully trained model. We will factor that into assessment.

### Assessment

The final project will be assessed out of 70 points. 20 of the points are already allocated to the description (this is basically automatic if it conforms to what is asked). For the remaining 50 points, each sub-team/contributor will be assessed separately for their individual notebooks. We will assess effort based on a combination of git commit histories, as well as documentation of effort in the form of initials added to sections within notebooks or other repo files (e.g. .py).

Points will be assigned as follows:

-   Quality of notebook (20 points). Does the team/sub-team notebook conform to the specifications set out above, and is the writing, code, and figures clear?

    -   An extra **2.5 points** will be awarded to teams that import their main code into analytical steps, rather than rely on all code compiled in notebook cells.

-   Quality of results (20 points): Did the team demonstrate good progress, sound results, and analysis. I.e. did they get their inputs formatted correctly, ingested into the model, train and evaluate a model, and demonstrate a prediction?

    -   As mentioned above, the ability to achieve all these ingredients will vary between groups and teams, so we will factor those differences into our assessments under this category.

    -   If a group can't get all the way though model training and prediction, we will evaluate the degree of team progress given project difficulty. Did the team do the best job they could to get as far as they could? Did they try several approaches to overcome problems? Did they adequately document bottlenecks and difficulties? Did they wrap up the project at a point from which further efforts could be readily taken up after submission?

-   Quality of discussion (10 points): This will assess the quality of insights provided by the team into their results. Does the teams assessment of results against expectations demonstrate understanding of the model, workflow, and analysis. Does the discussion explain likely reasons for bottlenecks/difficulties/unusual or unexpected findings?
