---
title: "More on Semantic Segmentation with CNNs"
toc: true
toc-depth: 6
number-sections: true
number-depth: 6
format: html
bibliography: references.bib
csl: ecology.csl
engine: jupyter
execute:
   enabled: true
---

## Overview

In the previous section and its associated practicals and assignment, we learned some of the basics of CNNs used for semantic segmentation, while learning more about the process of feeding data to a model.  At the very end of the chapter, we mentioned that there are other important architectures out there beyond the encoder-decoder networks, and we pointed you to some readings on these. In this section, we are going to learn a little more about these, and some of their key ingredients. 

## Increasing the receptive field
In the previous section we learned about architectures that mostly use ordinary convolutions followed by pooling to build up more comprehensive features as the network deepens. The deeper the network gets, the larger it's effective receptive field becomes--that is, its learns from a larger area of the input image. In the case of satellite imagery, the spatial context is crucial for semantic segmentation tasks. The images captured by satellites cover large areas and can contain many objects of interest that need to be identified and segmented. A large enough RF ensures the model can capture the relevant contextual information to better establish the spatial relationships between objects in the image, leading to better segmentation results and improved accuracy. 

However, as we have seen, getting really deep can be difficult, and the receptive field can therefore get only so large (see @fig-erfcnn), limiting the spatial context that the network can learn from, and therefore increasing error rates in pixel classifications [@khallaghiReviewTechnicalFactors2023a]. Furthermore, after all that pooling, to do semantic segmentation, you have to recover the input image dimensions, which requires a decoder of some sort that uses transposed convolutions, unpooling, etc. (as we have already learned).

Furthermore, there is a point where increasing the size of the convolutional kernel and the stride does not lead to further improvements in performance (also see @fig-erfcnn). This is because increasing the RF beyond a certain point can lead to the loss of fine-grained details and local information in the image.

![The relationship between the ERF of various architectures and their accuracies against the ImageNet benchmark. Although this graph suggest that there is a limited accuracy benefit to increasing the ERF beyond a certain area, note that this is for image classification, rather than semantic segmentation, and also that the maximum ERF is only 6% of the total area of a typical 224x224 input image. [Source](https://distill.pub/2019/computing-receptive-fields/?ref=https://githubhelp.com)](images/erf-cnns.png){#fig-erfcnn}

Given these complications, other approaches have been developed to either increase the spatial context the network can learn, and/or to make it easier to maintain or recover the original (spatial) resolution of input imagery. 

### Pyramid strategies 
One such approach is based on using pyramid-based approaches, in which a module consisting of multiple branches is used to examine different spatial scales, ranging from the global to the local, with the goal of improving the model's dense predictions. An example of this approach is the pyramid pooling module implemented as part of PSPNet [@zhaoPyramidSceneParsing2017a]. This module is situated at the base of a CNN backbone (the authors used several flavors of  ResNet), and consists of 4 parallel branches that first apply average pooling to the output feature maps from the last layer of the backbone, each of which examines a different set of scales, ranging from a set of smaller sub-regions (e.g. 16) to the entire feature map, improving and broadening the understanding of spatial context. These pooled features are then passed these through 1X1 convolutions, followed by batch normalization and ReLu activation (@fig-psp), after which the resulting feature maps, which vary in number, undergo bilinear interpolation to the dimensions of the inputs coming in from the base of the CNN, are concatenated together with each other and the original unpooled input feature maps. These features are all then interpolated back up to the resolution of the original input image, and then passed through additional convolutional layers to a final classification. 

![A schematic of PSPNet, featuring the Pyramid Parsing Module [from @zhaoPyramidSceneParsing2017a].](images/psp.png){#fig-psp}

This structure enabled PSPNet to outperform a baseline model on semantic segmentation of imagery in the [PASCAL VOC 2012](http://host.robots.ox.ac.uk/pascal/VOC/voc2012/) dataset, as shown in @fig-pspresults, which illustrates the sharper and more complete segmentations by PSPnet. 

![Segmentation results from PSPNet compared to a baseline model [from @zhaoPyramidSceneParsing2017a].](images/psp-net-results.png){#fig-pspresults}

### Dilated convolutions
An alternative way to increase the receptive field (RF) while improving the ability to recover spatial resolution is to minimize the amount of downsampling that you do, and let the kernel do more work. In this case, we are talking about dilated convolutions, or atrous convolutions. Atrous is a French word that means with holes, and, in as you can see from @fig-dilatedconv below, dilated convolution have gaps, or holes, between cells in the kernels. The size of the gaps are controlled by the dilation rate $r$. The larger the $r$, the greater the area observed by the kernel, and the larger the gaps. Obviously, the gaps means that the kernel is ignoring the areas between the kernel, but the kernel can leverage the typically strong correlations between adjacent pixels to learn without losing information about the scene. And it achieves the larger RF without increasing the number of parameters, and expanding the dilation rate in each successive layer expands the effective RF exponentially [@yuMultiScaleContextAggregation2016]. 

![A series of dilated convolutions, showing the effect on the receptive field (blue shading) by increasing dilations (1, 2, and 3, in panels A, B, C) applied in successive layers [from @yuMultiScaleContextAggregation2016].](images/dilated-conv.png){#fig-dilatedconv}

::: {.callout-tip}
## Calculating the Effective Receptive Field (ERF) with Dilation
The RF of a single dilated convolution can be calculated as:

$$k+(k-1)(r-1)$${#eq-1}

```{python}
#| echo: false
r = 2
k = 3
rf = (k + (r-1) * (k-1))**2
```

With $k$ as the kernel, and $r$ as the dilation rate. This gives the single side of the RF, so to get the full area, square that. So, a 3x3 kernel with an $r$ of 2 will return a value of 5 from @eq-1, which will give a total RF of 25 pixels. 

We can calculate the ERF of a series of dilated convolutions by starting from the input and calculating the RF of subsequent layers recursively by adding the RF of the current layer to the RF of the previous layer. For the input (aka. layer 0) the RF is always 1. For the first layer in the network, the RF is equal to the size of the kernel.

$$ERF_{1} = k_1 + (k_1-1) \times (r_1 - 1)$${#eq-2}

In case we are using same padding in the first conv layer:

$$ERF_{2} = ERF_{1} + (k_2 + (k_2-1) \times (r_2 - 1)) \times s_1$${#eq-3}

Where $s$ is stride. If we are using valid convolution in the first layer:

$$ ERF_{2} = ERF_{1} + (k_2 + (k_2-1) \times (r_2 - 1)) \times s_1 - (p_1 - 1) $${#eq-4}

Here $p$ is padding. 

The following is a recursive formula for a valid network if we have same "padding" as part of the ERF calculation:

$$
ERF_L = \sum_{l=1}^{L} \left((k_l + (k_l-1) \times (r_l - 1)) \cdot \prod_{i=1}^{l-1} s_i \right) + 1
$${#eq-5}

This is the same formula if we do not have padding for all conv layers:

$$
ERF_L = \sum_{l=1}^{L} \left((k_l + (k_l-1) \times (r_l - 1)) \cdot \prod_{i=1}^{l-1} s_i - (p_i - 1) \right) + 1
$${#eq-6}

Here, $d_l$ is the dilation rate of layer $l$, $k_l$ is the kernel size, $s_i$ and $p_i$ are the stride and padding size of layer $i$, and $L$ is the current layer in the neural network. 

Note:

- We are providing the formulas above since there are several different approaches out there for calculating the receptive field. 
- Unlike @eq-1, @eq-2 - @eq-6 provide just a single side of the ERF.

For more information check these references, but their formulation of ERF might be a bit different: [1](https://arxiv.org/pdf/1705.07049.pdf), [2](https://distill.pub/2019/computing-receptive-fields/#return-from-other-network-operations)
:::

Dilated convolutions can have their problems, of course. One particular problem that can happen is that if you stack successive layers of dilated convolutions, you can end up with checkerboard artifacts, as shown in @fig-checkerboard.

![An illustration of how separation in the effective receptive fields can occur when sequential layers of dilated convolutions are used. In a, the left hand side illustrates the the fields of view that pixels at the top of the network have, while the righthand shows the fields of view for pixels at bottom of the network. In b, color-coding illustrates the receptive fields across three successive layers that result from this arrangment [from @khallaghiReviewTechnicalFactors2023a]](images/dilated-conv-checkerboard){#fig-checkerboard}

The effect of that checkerboarding on model results is shown in @fig-hamaguchi, presented in a paper by @hamaguchiEffectiveUseDilated2018, who implemented a special local feature extraction module, which consists of a stack of dilated convolutions that have progressively decreasing rates of dilation (from 3 to 1), which helps eliminate the artifacts. 

![An illustration of gridding artifacts from a semantic segmention by a model that uses dilation convolutions (center column), which are fixed by the addition of a module called local feature extraction [from @hamaguchiEffectiveUseDilated2018]. Front, S, D, and Large refer to different aspects of modification of a VGG-16 that were used in the experiments.](images/hamaguchi-lfe.png){#fig-hamaguchi}

There are many other approaches to implementing dilated convolutions, and these are summarized in @khallaghiReviewTechnicalFactors2023a.  For example, one of them is called hybrid dilated convolution, which divides dilated convolutional layers into groups (as in ResNeXt), with each group using a different dilation rate. Parallel branches of dilated convolutions are also commonly used, and features in the Atrous Spatial Pyramid Pooling Module (ASPP) that we will look at in Practical 4, which was introduced in the DeepLab family of models [@chenDeepLabSemanticImage2017; @chenEncoderDecoderAtrousSeparable2018]. We'll look at this here briefly in a little more detail. 

### ASPP and DeepLab

The DeepLab family of models have been reasonably widely applied for semantic segmentation tasks in Earth Observation. One example is in @chenEndtoEndOilSpillMonitoring2020, who used the model to detect oil spills in imagery. 

DeepLab has several incarnations, the most recent being DeepLab v3+ [@chenEncoderDecoderAtrousSeparable2018].  The ASPP module was introduced in the first DeepLab [@chenDeepLabSemanticImage2017], and as of the latest versions consists of 5 parallel layers, three of which are dilated convolution layers, with rates of 6, 12, and 18, along with a 1x1 convolutional layer and a global pooling layer(@fig-aspp A). The ASPP module is inserted after about block 3 or 4 of the encoder (which can be of several types, starting with ResNet), after the image has been downsampled by a factor of 8X (@fig-aspp B). The four convolutional layers maintain the same dimensions 8X downsampled relative to the input, while the global pooling is interpolated up to the resolution of the other four, and all 5 are concatenated together. In DeepLabV3, the outputs of the ASPP are passed through a 1X1 convolutional layer, then undergo bilinear upsampling to recover the scale of the input image, after which they are passed through a final set of convolutions followed by classification (@fig-aspp B).  DeepLabV3+ expands on this by adopting features of an encoder-decoder architecture. It does this by interpolating the output of the ASPP by a factor of 4X, then concatenating it with the adjacent layer of the encoder that is 1/4 of the resolution of the input, followed by a final 4X interpolation to the original input resolution, and then the final block of convolutional layers and classification (@fig-aspp C & @fig-deeplabv3).   

![The structure of the atrous spatial pyramid pooling module (ASPP), [A, from @chenRethinkingAtrousConvolution2017]. The ASPP is inserted into the network after several blocks of the encoder (B,C), after which it undergoes interpolation followed by convolution and classification. Panels B and C respectively show the structures of DeepLabV3 and DeepLabV3+ [from @chenEncoderDecoderAtrousSeparable2018] ](images/aspp.png){#fig-aspp}

![The original schematic for DeepLabV3+ [@chenEncoderDecoderAtrousSeparable2018]](images/deeplabv3plus.png){#fig-deeplabv3}


