"""
Import the image catalog into Supabase.

    catalog_output/folder_summary.csv     -> public.folders
    catalog_output/image_manifest.csv.gz  -> public.images
    catalog_output/qa_log.csv (optional)  -> public.qa_log

The manifest has no folder_name or relative_path column (catalog_images.py
leaves them out), so each image's folder is recovered from its filename and
proven by its image_id, which catalog_images.py computes as
sha1("<folder>/<filename>")[:16]. The database builds relative_path -- the R2
object key -- as "<folder>/<filename>" with a forward slash.

Every row is checked before anything is written: each image must hash to a
folder in the summary, repeat that folder's metadata exactly, and the
summary's per-folder image counts and dimension ranges must match the
manifest. Then the data is COPYed into temporary staging tables, and one
transaction brings the live tables in line with them (insert new rows, update
changed ones, delete ones no longer in the catalog) and re-checks the counts
before committing. A failed run rolls back and leaves the previous data as it
was. The reserved images.label column is never touched.

Usage (from ProjectCode/):
    python deploy/import_to_supabase.py --dry-run   # check the files, estimate size; writes nothing
    python deploy/import_to_supabase.py             # import
"""

import argparse
import csv
import gzip
import hashlib
import os
import sys
import time
from pathlib import Path

import psycopg
from dotenv import load_dotenv

from apply_migrations import PROJECT_DIR, connect, describe, get_db_url

CATALOG_DIR = PROJECT_DIR / "catalog_output"
SIZE_LIMIT_MB = 350  # stay well under Supabase's 500 MB free-tier database limit
MB = 1024 * 1024

# public.folders columns, in folder_summary.csv order, with their types.
FOLDER_COLUMNS = [
    ("folder_name", "text"), ("site_raw", "text"), ("site_normalized", "text"),
    ("water_body_type", "text"), ("date", "text"), ("magnification", "text"),
    ("sample_code", "text"), ("capture_mode", "text"), ("dilution", "text"),
    ("is_pp", "bool"), ("pp_of_folder", "text"), ("image_count", "int"),
    ("unreadable_count", "int"), ("min_width", "int"), ("max_width", "int"),
    ("min_height", "int"), ("max_height", "int"),
]
FOLDER_NOT_NULL = {"folder_name", "is_pp", "image_count", "unreadable_count"}

# public.images columns loaded from the manifest. relative_path is generated by
# the database and label is reserved, so neither is loaded.
IMAGE_COLUMNS = ["image_id", "folder_name", "filename", "width", "height",
                 "file_size_bytes", "format", "mode", "is_readable", "source_dataset"]
MANIFEST_REQUIRED = ["image_id", "filename", "width", "height", "file_size_bytes",
                     "format", "mode", "is_readable", "source_dataset"]
# Manifest columns that repeat the folder's metadata: checked, not stored.
FOLDER_LEVEL_COLUMNS = ["site_raw", "site_normalized", "water_body_type", "date",
                        "magnification", "sample_code", "capture_mode", "dilution", "is_pp"]
# Labeling isn't built yet, so these must be empty rather than silently dropped.
LABEL_COLUMNS = ["label", "labeled_by", "labeled_date"]


class DataError(Exception):
    pass


# --- Reading and checking the catalog files ------------------------------------

def as_text(value):
    return value if value != "" else None


def as_int(value, where):
    if value == "":
        return None
    try:
        return int(value)
    except ValueError:
        raise DataError(f"{where}: expected a whole number, got {value!r}") from None


def as_bool(value, where):
    lowered = value.strip().lower()
    if lowered in ("true", "t", "1"):
        return True
    if lowered in ("false", "f", "0"):
        return False
    raise DataError(f"{where}: expected True or False, got {value!r}")


CONVERTERS = {
    "text": lambda v, where: as_text(v),
    "int": as_int,
    "bool": as_bool,
}


def image_id_for(folder_name: str, filename: str) -> str:
    """Same hash as catalog_images.image_id_for() over its "<folder>/<file>" path."""
    return hashlib.sha1(f"{folder_name}/{filename}".encode("utf-8")).hexdigest()[:16]


def load_folders(path: Path):
    """Returns (raw rows by name, converted rows by name, rows to COPY, ignored columns)."""
    with open(path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        header = reader.fieldnames or []
        missing = [c for c, _ in FOLDER_COLUMNS if c not in header]
        if missing:
            raise DataError(f"{path.name} is missing column(s): {', '.join(missing)}")
        known = {c for c, _ in FOLDER_COLUMNS}
        ignored = [c for c in header if c not in known]

        raw, converted, copy_rows = {}, {}, []
        for line, row in enumerate(reader, start=2):
            where = f"{path.name} line {line}"
            name = row["folder_name"]
            if name in raw:
                raise DataError(f"{where}: duplicate folder_name {name!r}")
            values = {}
            for col, kind in FOLDER_COLUMNS:
                values[col] = CONVERTERS[kind](row[col], f"{where}, {col}")
                if values[col] is None and col in FOLDER_NOT_NULL:
                    raise DataError(f"{where}: {col} is empty")
            raw[name] = row
            converted[name] = values
            copy_rows.append(tuple(values[c] for c, _ in FOLDER_COLUMNS))
    return raw, converted, copy_rows, ignored


def resolve_folder(filename, image_id, folder_names, folders_longest_first):
    """The folder whose "<folder>/<filename>" hashes to image_id, or None."""
    stem = filename.rsplit("_", 1)[0]  # "<folder>_00012.png" -> "<folder>"
    if stem in folder_names and image_id_for(stem, filename) == image_id:
        return stem
    for name in folders_longest_first:  # slow path for names that break the pattern
        if image_id_for(name, filename) == image_id:
            return name
    return None


def load_images(path: Path, folders_raw: dict):
    """Returns (rows to COPY, per-folder stats, ignored columns)."""
    folder_names = set(folders_raw)
    folders_longest_first = sorted(folder_names, key=len, reverse=True)
    stats = {name: {"image_count": 0, "unreadable_count": 0, "min_width": None,
                    "max_width": None, "min_height": None, "max_height": None}
             for name in folder_names}
    rows, seen = [], set()

    with gzip.open(path, "rt", newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        header = reader.fieldnames or []
        missing = [c for c in MANIFEST_REQUIRED if c not in header]
        if missing:
            raise DataError(f"{path.name} is missing column(s): {', '.join(missing)}")
        folder_level = [c for c in FOLDER_LEVEL_COLUMNS if c in header]
        label_cols = [c for c in LABEL_COLUMNS if c in header]
        # Older/newer manifests may carry these; if so they must agree.
        has_folder_col = "folder_name" in header
        has_path_col = "relative_path" in header
        known = set(MANIFEST_REQUIRED + FOLDER_LEVEL_COLUMNS + LABEL_COLUMNS
                    + ["folder_name", "relative_path"])
        ignored = [c for c in header if c not in known]

        for line, row in enumerate(reader, start=2):
            where = f"{path.name} line {line}"
            image_id, filename = row["image_id"], row["filename"]
            if image_id in seen:
                raise DataError(f"{where}: duplicate image_id {image_id}")
            seen.add(image_id)

            folder = resolve_folder(filename, image_id, folder_names, folders_longest_first)
            if folder is None:
                raise DataError(
                    f"{where}: no folder in folder_summary.csv matches image_id {image_id} "
                    f"for {filename!r}. Are the manifest and the summary from the same catalog run?")
            if has_folder_col and row["folder_name"] and row["folder_name"] != folder:
                raise DataError(f"{where}: folder_name {row['folder_name']!r} doesn't match "
                                f"the folder its image_id hashes to ({folder!r})")
            if has_path_col and row["relative_path"] and \
                    row["relative_path"].replace("\\", "/") != f"{folder}/{filename}":
                raise DataError(f"{where}: relative_path {row['relative_path']!r} doesn't match "
                                f"'{folder}/{filename}'")

            summary_row = folders_raw[folder]
            for col in folder_level:
                if row[col] != summary_row[col]:
                    raise DataError(f"{where}: {col} is {row[col]!r} but folder_summary.csv "
                                    f"has {summary_row[col]!r} for {folder!r}")
            for col in label_cols:
                if row[col].strip():
                    raise DataError(f"{where}: {col} is set ({row[col]!r}), but importing "
                                    f"labels isn't supported yet")

            width = as_int(row["width"], f"{where}, width")
            height = as_int(row["height"], f"{where}, height")
            is_readable = as_bool(row["is_readable"], f"{where}, is_readable")
            rows.append((
                image_id, folder, filename, width, height,
                as_int(row["file_size_bytes"], f"{where}, file_size_bytes"),
                as_text(row["format"]), as_text(row["mode"]), is_readable,
                as_text(row["source_dataset"]),
            ))

            s = stats[folder]
            s["image_count"] += 1
            if not is_readable:
                s["unreadable_count"] += 1
            if width is not None and height is not None:
                s["min_width"] = width if s["min_width"] is None else min(s["min_width"], width)
                s["max_width"] = width if s["max_width"] is None else max(s["max_width"], width)
                s["min_height"] = height if s["min_height"] is None else min(s["min_height"], height)
                s["max_height"] = height if s["max_height"] is None else max(s["max_height"], height)
    return rows, stats, ignored


def check_folder_totals(folders: dict, stats: dict) -> None:
    """folders_visible serves the summary's counts, so they must match the manifest."""
    problems = []
    for name, folder in folders.items():
        for key, actual in stats[name].items():
            if folder[key] != actual:
                problems.append(f"{name}: {key} is {folder[key]} in folder_summary.csv "
                                f"but {actual} in the manifest")
    if problems:
        shown = "\n  ".join(problems[:10])
        more = f"\n  ... and {len(problems) - 10} more" if len(problems) > 10 else ""
        raise DataError(f"folder_summary.csv doesn't match image_manifest.csv.gz:\n  {shown}{more}")


def load_qa_log(path: Path):
    """Rows for public.qa_log, or None if there's no qa_log.csv."""
    if not path.exists():
        return None
    with open(path, newline="", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        header = reader.fieldnames or []
        missing = [c for c in ("level", "target", "detail") if c not in header]
        if missing:
            raise DataError(f"{path.name} is missing column(s): {', '.join(missing)}")
        return [(row["level"] or "INFO", as_text(row["target"]), as_text(row["detail"]))
                for row in reader]


# --- Size estimate -------------------------------------------------------------
# Postgres stores each row as a 24-byte header plus its values (text: 1 length
# byte + the bytes; ints aligned to their size), plus a 4-byte slot on an 8 KB
# page. Close enough to decide whether we fit; the real size is printed after.

def _align(n: int, to: int) -> int:
    return (n + to - 1) // to * to


def _text(value) -> int:
    if value is None:
        return 0
    n = len(value.encode("utf-8"))
    return 1 + n if n < 127 else 4 + n


def estimate_images_table(rows) -> dict:
    heap = stage = 0
    for image_id, folder, filename, width, height, size, fmt, mode, _readable, source in rows:
        head = 24 + _text(image_id) + _text(folder) + _text(filename)
        tail_start = head + _text(f"{folder}/{filename}")  # relative_path, stored

        def rest(offset):
            offset = _align(offset, 4) + 8          # width, height
            offset = _align(offset, 8) + 8          # file_size_bytes
            offset += _text(fmt) + _text(mode) + 1 + _text(source)
            return _align(offset, 8) + 4            # + line pointer

        heap += rest(tail_start)
        stage += rest(head)                          # staging copy has no relative_path
    page_overhead = 8192 / (8192 - 24)
    n = len(rows)
    return {
        "heap": heap * page_overhead,
        "primary_key": n * 36 / 0.9,       # 16-char key entries, ~90% full pages
        "folder_index": n * 7 / 0.9,       # deduplicated: ~600 distinct values
        "staging": stage * page_overhead,  # temporary, dropped at commit
    }


# --- Database ------------------------------------------------------------------

def db_snapshot(conn) -> dict:
    size = conn.execute("select pg_database_size(current_database())").fetchone()[0]
    ours = conn.execute(
        "select coalesce(sum(pg_total_relation_size(c)), 0)::bigint from unnest("
        "array['public.folders', 'public.images', 'public.qa_log']::regclass[]) as c"
    ).fetchone()[0]
    counts = {t: conn.execute(f"select count(*) from public.{t}").fetchone()[0]
              for t in ("folders", "images", "qa_log")}
    return {"size": size, "catalog_tables": ours, "baseline": size - ours, "counts": counts}


def quoted(cols):
    return ", ".join(f'"{c}"' for c in cols)


def copy_rows(conn, table: str, columns, rows, label: str) -> None:
    started = time.time()
    with conn.cursor().copy(f"copy {table} ({quoted(columns)}) from stdin") as copy:
        for i, row in enumerate(rows, start=1):
            copy.write_row(row)
            if i % 100_000 == 0:
                print(f"    {label}: {i:,} rows sent")
    print(f"    {label}: {len(rows):,} rows copied in {time.time() - started:.0f}s")


def upsert_sql(table: str, key: str, columns, source: str) -> str:
    """Insert new rows, update rows whose values changed, leave the rest alone."""
    others = [c for c in columns if c != key]
    assignments = ", ".join(f'"{c}" = excluded."{c}"' for c in others)
    current = ", ".join(f't."{c}"' for c in others)
    incoming = ", ".join(f'excluded."{c}"' for c in others)
    return (
        f"insert into {table} as t ({quoted(columns)}) "
        f"select {quoted(columns)} from {source} "
        f'on conflict ("{key}") do update set {assignments} '
        f"where ({current}) is distinct from ({incoming})"
    )


def scalar(conn, sql: str):
    return conn.execute(sql).fetchone()[0]


def run_import(conn, folder_rows, image_rows, qa_rows) -> dict:
    folder_cols = [c for c, _ in FOLDER_COLUMNS]
    changes = {}
    with conn.transaction():
        conn.execute("set local statement_timeout = '30min'")
        # One import at a time.
        conn.execute("select pg_advisory_xact_lock(hashtext('import_to_supabase'))")

        conn.execute("create temp table stage_folders (like public.folders) on commit drop")
        conn.execute("""
            create temp table stage_images (
              image_id text not null, folder_name text not null, filename text not null,
              width integer, height integer, file_size_bytes bigint, format text,
              mode text, is_readable boolean not null, source_dataset text
            ) on commit drop""")
        print("  Uploading to staging tables ...")
        copy_rows(conn, "stage_folders", folder_cols, folder_rows, "folders")
        copy_rows(conn, "stage_images", IMAGE_COLUMNS, image_rows, "images")
        conn.execute("analyze stage_folders")
        conn.execute("analyze stage_images")

        print("  Applying changes to the live tables ...")
        for table, stage, key in (("folders", "stage_folders", "folder_name"),
                                  ("images", "stage_images", "image_id")):
            changes[table] = {
                "new": scalar(conn, f"select count(*) from {stage} s where not exists "
                                    f"(select 1 from public.{table} t where t.{key} = s.{key})"),
                "removed": scalar(conn, f"select count(*) from public.{table} t where not exists "
                                        f"(select 1 from {stage} s where s.{key} = t.{key})"),
            }

        # Folder foreign keys are checked at commit, so this order is only for clarity.
        upserted = conn.execute(upsert_sql("public.folders", "folder_name", folder_cols,
                                           "stage_folders")).rowcount
        changes["folders"]["changed"] = upserted - changes["folders"]["new"]
        conn.execute("delete from public.images t where not exists "
                     "(select 1 from stage_images s where s.image_id = t.image_id)")
        upserted = conn.execute(upsert_sql("public.images", "image_id", IMAGE_COLUMNS,
                                           "stage_images")).rowcount
        changes["images"]["changed"] = upserted - changes["images"]["new"]
        conn.execute("delete from public.folders t where not exists "
                     "(select 1 from stage_folders s where s.folder_name = t.folder_name)")

        if qa_rows is not None:
            conn.execute("delete from public.qa_log")
            copy_rows(conn, "public.qa_log", ["level", "target", "detail"], qa_rows, "qa_log")

        print("  Checking before commit ...")
        n_folders = scalar(conn, "select count(*) from public.folders")
        n_images = scalar(conn, "select count(*) from public.images")
        mismatched = scalar(conn, """
            select count(*) from public.folders f
            left join (select folder_name, count(*) as n from public.images group by folder_name) c
              using (folder_name)
            where coalesce(c.n, 0) <> f.image_count""")
        problems = []
        if n_folders != len(folder_rows):
            problems.append(f"folders has {n_folders:,} rows, expected {len(folder_rows):,}")
        if n_images != len(image_rows):
            problems.append(f"images has {n_images:,} rows, expected {len(image_rows):,}")
        if mismatched:
            problems.append(f"{mismatched} folder(s) have an image_count that doesn't match their images")
        if problems:
            raise DataError("post-load check failed, rolling back: " + "; ".join(problems))
    return changes


def print_estimate(est: dict, baseline: int, baseline_measured: bool) -> float:
    images_total = est["heap"] + est["primary_key"] + est["folder_index"]
    total = baseline + images_total + 1 * MB  # folders + qa_log are well under 1 MB
    peak = total + est["staging"]
    source = "measured" if baseline_measured else "typical new project, not measured"
    print("Estimated database size after import:")
    print(f"  images table       ~{images_total / MB:,.0f} MB  (rows {est['heap'] / MB:,.0f}, "
          f"primary key {est['primary_key'] / MB:,.0f}, folder index {est['folder_index'] / MB:,.0f})")
    print(f"  folders + qa_log   <1 MB")
    print(f"  everything else    ~{baseline / MB:,.0f} MB  ({source})")
    print(f"  total              ~{total / MB:,.0f} MB   (limit for this project: {SIZE_LIMIT_MB} MB; "
          f"Supabase free tier: 500 MB)")
    print(f"  peak while loading ~{peak / MB:,.0f} MB   (temporary staging copy, dropped at commit)")
    return total / MB


def main():
    parser = argparse.ArgumentParser(description="Import the image catalog into Supabase.")
    parser.add_argument("--dry-run", action="store_true",
                        help="check the files and estimate the size; write nothing")
    parser.add_argument("--summary", type=Path, default=CATALOG_DIR / "folder_summary.csv")
    parser.add_argument("--manifest", type=Path, default=CATALOG_DIR / "image_manifest.csv.gz")
    parser.add_argument("--qa-log", type=Path, default=CATALOG_DIR / "qa_log.csv")
    args = parser.parse_args()

    started = time.time()
    print("Reading and checking the catalog files ...")
    try:
        folders_raw, folders, folder_rows, ignored_f = load_folders(args.summary)
        image_rows, stats, ignored_i = load_images(args.manifest, folders_raw)
        check_folder_totals(folders, stats)
        qa_rows = load_qa_log(args.qa_log)
    except (DataError, OSError) as exc:
        sys.exit(f"ERROR: {exc}\nNothing was written.")

    empty = sum(1 for f in folders.values() if f["image_count"] == 0)
    print(f"  {args.summary.name}: {len(folder_rows):,} folders "
          f"({empty} with no images, hidden by folders_visible)")
    print(f"  {args.manifest.name}: {len(image_rows):,} images, every image_id matches "
          f"'<folder>/<filename>', per-folder counts and sizes match the summary")
    print(f"  {args.qa_log.name}: " + (f"{len(qa_rows):,} entries" if qa_rows is not None
                                      else "not found, the qa_log table will be left as it is"))
    for name, cols in ((args.summary.name, ignored_f), (args.manifest.name, ignored_i)):
        if cols:
            print(f"  NOTE: {name} column(s) not stored: {', '.join(cols)}")

    est = estimate_images_table(image_rows)
    load_dotenv(PROJECT_DIR / ".env")
    have_db = bool(os.environ.get("SUPABASE_DB_URL", "").strip())

    if args.dry_run:
        snapshot = None
        if have_db:
            url = get_db_url()
            print(f"Reading current state of {describe(url)} (read-only) ...")
            with connect(url) as conn:
                conn.read_only = True
                with conn.transaction():
                    snapshot = db_snapshot(conn)
            c = snapshot["counts"]
            print(f"  now: {snapshot['size'] / MB:,.1f} MB, {c['folders']:,} folders, "
                  f"{c['images']:,} images, {c['qa_log']:,} QA entries")
        baseline = snapshot["baseline"] if snapshot else 30 * MB
        total_mb = print_estimate(est, baseline, snapshot is not None)
        if total_mb > SIZE_LIMIT_MB:
            print(f"WARNING: over the {SIZE_LIMIT_MB} MB limit; the real import will refuse to run.")
        print(f"Dry run finished in {time.time() - started:.0f}s. Nothing was written.")
        return

    url = get_db_url()
    print(f"Connecting to {describe(url)} ...")
    with connect(url) as conn:
        before = db_snapshot(conn)
        total_mb = print_estimate(est, before["baseline"], True)
        if total_mb > SIZE_LIMIT_MB:
            sys.exit(f"ERROR: the estimated size is over {SIZE_LIMIT_MB} MB. Nothing was written.")

        print("Importing ...")
        try:
            changes = run_import(conn, folder_rows, image_rows, qa_rows)
        except (DataError, psycopg.Error) as exc:
            sys.exit(f"ERROR: {exc}\nRolled back; the database is unchanged.")
        conn.execute("analyze public.folders, public.images")

        after = db_snapshot(conn)
        print("Committed.")
        for table in ("folders", "images"):
            ch = changes[table]
            print(f"  {table}: {ch['new']:,} added, {ch['changed']:,} changed, "
                  f"{ch['removed']:,} removed -> {after['counts'][table]:,} rows "
                  f"(source: {len(folder_rows if table == 'folders' else image_rows):,})")
        print(f"  qa_log: {after['counts']['qa_log']:,} rows"
              + ("" if qa_rows is not None else " (not changed, no qa_log.csv)"))
        print(f"  database size: {after['size'] / MB:,.1f} MB "
              f"(was {before['size'] / MB:,.1f} MB; pg_database_size)")

        stats_row = conn.execute("select * from public.dashboard_stats")
        names = [d.name for d in stats_row.description]
        values = stats_row.fetchone()
        print("  dashboard_stats: " + ", ".join(f"{n}={v}" for n, v in zip(names, values)))
    print(f"Done in {time.time() - started:.0f}s.")


if __name__ == "__main__":
    main()
